services:
  database:
    image: postgres:13.5
    environment:
      - POSTGRES_DB=contact
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql